# permissions for end users to view staticwebpages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticwebpage-viewer-role
rules:
- apiGroups:
  - bobthebuilder.my.domain
  resources:
  - staticwebpages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bobthebuilder.my.domain
  resources:
  - staticwebpages/status
  verbs:
  - get
